---
- hosts: staging
  gather_facts: false
  remote_user: "{{ secure_deployment_user }}"
  roles:
    - ansible-locale
    - ansible-python
    - ansible-memcached
    - ansible-nginx
    - ansible-postgres
    - ansible-django-site
    - ansible-uwsgi
